In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action="ignore")

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mpl
mpl.rcParams["axes.unicode_minus"] = False

import urllib.request as req
from urllib.request import urlopen
from urllib.error import HTTPError, URLError
import urllib.parse
from bs4 import BeautifulSoup
import requests

In [28]:
##### 3사매출- 모바일

sales3C_mobile = pd.read_csv("checkpoint/sales_3C_mobile_sum_checkpoint.csv", index_col = 0)
sales3C_mobile
sales3C_mobile.columns = ["3사 Mobile 매출"]
sales3C_mobile

        3사 Mobile 매출
1Q2017  1.907603e+11
2Q2017  5.611863e+11
3Q2017  9.005560e+11
4Q2017  8.958130e+11
1Q2018  7.269950e+11
2Q2018  5.324043e+11
3Q2018  5.921097e+11
4Q2018  5.627087e+11
1Q2019  3.239240e+11
2Q2019  3.402707e+11
3Q2019  3.123433e+11
4Q2019  4.391200e+11
1Q2020  1.048860e+12
2Q2020  8.875083e+11
3Q2020  1.356090e+12
4Q2020  1.161611e+12
1Q2021  9.742760e+11
2Q2021  8.964657e+11
3Q2021  8.974830e+11

In [29]:
##### 3사매출- PC

sales3C_pc = pd.read_csv("checkpoint/sales_3C_pc_sum_checkpoint.csv", index_col = 0)
sales3C_pc

sales3C_pc.columns = ["3사 PC매출"]
sales3C_pc

             3사 PC매출
1Q2017  9.447470e+11
2Q2017  7.456180e+11
3Q2017  9.349635e+11
4Q2017  7.834570e+11
1Q2018  7.692030e+11
2Q2018  7.308540e+11
3Q2018  1.092198e+12
4Q2018  7.497090e+11
1Q2019  9.549040e+11
2Q2019  8.318520e+11
3Q2019  1.105410e+12
4Q2019  9.208410e+11
1Q2020  1.593336e+12
2Q2020  1.240709e+12
3Q2020  1.453089e+12
4Q2020  1.306676e+12
1Q2021  1.815808e+12
2Q2021  1.166518e+12
3Q2021  1.553097e+12

In [43]:
##### 날씨

temperature = pd.read_csv("checkpoint/temperature_checkpoint.csv", index_col = 0)
temperature = temperature.T
temperature

         평균기온(°C)
1Q2017   2.744561
2Q2017  17.886667
3Q2017  24.000000
4Q2017   7.394386
1Q2018   2.030175
2Q2018  17.555088
3Q2018  24.640351
4Q2018   7.538947
1Q2019   3.451228
2Q2019  17.073776
3Q2019  24.010140
4Q2019   9.167368
1Q2020   4.849123
2Q2020  16.954737
3Q2020  23.112281
4Q2020   7.912281
1Q2021   4.052632
2Q2021  17.236268
3Q2021  24.183158

In [70]:
###### 마케팅 비용

marketing_cost = pd.read_csv("checkpoint/marketing_cost_checkpoint.csv", index_col = 0)
marketing_cost = marketing_cost.T
marketing_cost = marketing_cost.drop(index=["기업 별 합계"], axis=0)

marketing_cost_sum = marketing_cost.loc[:, "분기별 합계"]
marketing_cost_sum

1Q2017    1.858444e+11
2Q2017    2.045050e+11
3Q2017    2.372769e+11
4Q2017    2.862413e+11
1Q2018    2.416348e+11
2Q2018    2.368410e+11
3Q2018    2.473202e+11
4Q2018    2.762086e+11
1Q2019    2.448007e+11
2Q2019    2.597875e+11
3Q2019    2.346793e+11
4Q2019    2.820933e+11
1Q2020    2.347716e+11
2Q2020    2.838224e+11
3Q2020    3.233597e+11
4Q2020    3.749360e+11
1Q2021    2.914224e+11
2Q2021    3.873891e+11
3Q2021    4.316472e+11
Name: 분기별 합계, dtype: float64

In [64]:
marketing_cost

기업명,넥슨,엔씨소프트,넷마블,카카오게임즈,NHN,컴투스,데브시스터즈,그라비티,펄어비스,웹젠,네오위즈,위메이드,게임빌,선데이토즈,엠게임,베스파,마케팅 비용
1Q2017,3.173000e+10,1.270100e+10,7.840000e+10,2.495900e+10,2.043700e+09,1.202000e+10,1.432000e+09,3.007771e+09,1.254000e+09,1.831000e+09,3.140000e+09,9.059000e+09,1.866000e+09,3.800000e+08,43233000.0,1.977658e+09,1.858444e+11
2Q2017,3.650000e+10,2.411500e+10,8.240000e+10,2.192900e+10,2.087900e+09,1.900700e+10,3.250000e+08,3.007771e+09,1.220000e+09,2.528000e+09,3.153000e+09,1.015000e+09,4.056000e+09,2.560000e+08,927644000.0,1.977658e+09,2.045050e+11
3Q2017,5.122000e+10,2.204300e+10,1.010000e+11,3.346000e+10,2.069000e+09,1.390000e+10,9.200000e+07,3.007771e+09,1.455000e+09,9.700000e+08,3.844000e+09,5.630000e+08,1.190000e+09,4.110000e+08,74484000.0,1.977658e+09,2.372769e+11
4Q2017,5.910000e+10,2.415100e+10,1.194000e+11,3.613000e+10,2.176100e+09,2.130000e+10,6.210000e+08,3.007771e+09,5.212000e+09,1.669000e+09,3.742000e+09,7.570000e+08,4.299000e+09,2.625000e+09,73813000.0,1.977658e+09,2.862413e+11
1Q2018,5.631000e+10,1.077100e+10,7.470000e+10,4.794100e+10,1.593400e+09,1.330000e+10,3.400000e+07,4.136462e+09,1.050600e+10,1.735000e+09,4.217000e+09,6.660000e+08,4.643000e+09,1.741000e+09,40739000.0,9.300195e+09,2.416348e+11
2Q2018,5.610000e+10,1.497300e+10,7.860000e+10,4.531100e+10,1.422300e+09,1.870000e+08,2.670000e+08,4.136462e+09,9.195000e+09,4.739000e+09,5.534000e+09,1.830000e+09,1.186000e+09,3.980000e+09,80000000.0,9.300195e+09,2.368410e+11
3Q2018,6.279000e+10,1.651300e+10,8.510000e+10,3.627400e+10,1.412500e+09,1.790000e+08,1.930000e+08,4.136462e+09,9.959000e+09,4.536000e+09,5.873000e+09,6.498000e+09,2.998000e+09,1.496000e+09,62007000.0,9.300195e+09,2.473202e+11
4Q2018,6.846000e+10,1.589400e+10,7.340000e+10,5.453800e+10,1.390900e+09,2.170000e+10,8.700000e+08,4.136462e+09,1.002900e+10,2.380000e+09,8.306000e+09,1.780000e+09,3.615000e+09,2.980000e+08,111071000.0,9.300195e+09,2.762086e+11
1Q2019,5.194000e+10,1.898700e+10,6.280000e+10,3.294700e+10,1.210100e+09,1.460000e+10,3.030000e+08,2.493422e+09,3.025100e+10,2.922000e+09,9.750000e+09,4.790000e+09,2.334000e+09,3.420000e+08,111147000.0,9.019984e+09,2.448007e+11
2Q2019,5.500000e+10,2.423000e+10,8.360000e+10,3.850000e+10,1.467600e+09,1.640000e+10,1.424000e+09,2.493422e+09,1.543500e+10,4.717000e+08,8.502000e+09,1.830000e+09,1.924000e+09,1.193000e+09,59612000.0,7.257181e+09,2.597875e+11
3Q2019,3.767000e+10,2.276600e+10,7.230000e+10,3.680000e+10,1.672000e+09,1.600000e+10,4.550000e+08,2.493422e+09,1.583500e+10,1.354000e+09,1.035200e+10,1.140000e+09,2.091000e+09,5.690000e+08,38523000.0,1.314333e+10,2.346793e+11
4Q2019,4.260000e+10,4.129100e+10,7.370000e+10,4.152600e+10,1.891100e+09,1.460000e+10,1.918000e+09,2.493422e+09,1.676000e+10,1.534000e+09,9.949000e+09,1.224000e+09,2.720000e+09,8.433000e+09,131194000.0,2.132255e+10,2.820933e+11
1Q2020,2.836000e+10,3.957300e+10,9.500000e+10,2.990000e+10,1.502600e+09,8.200000e+09,1.067000e+09,4.946807e+09,9.444000e+09,6.540000e+08,6.564000e+09,1.341000e+09,7.230000e+08,3.940000e+09,18850000.0,3.537390e+09,2.347716e+11
2Q2020,4.326000e+10,1.289800e+10,1.249000e+11,3.850000e+10,1.821900e+09,2.110000e+10,1.831000e+09,4.946807e+09,9.166000e+09,5.731000e+09,9.185000e+09,1.561000e+09,1.365000e+09,2.559000e+09,49317000.0,4.948341e+09,2.838224e+11
3Q2020,5.852000e+10,2.972300e+10,8.570000e+10,7.630000e+10,2.071400e+09,2.150000e+10,1.288000e+09,4.946807e+09,9.228000e+09,7.497000e+09,1.106200e+10,4.107000e+09,3.572000e+09,2.491000e+09,36013000.0,5.317439e+09,3.233597e+11
4Q2020,7.401000e+10,4.481300e+10,8.680000e+10,8.750000e+10,2.376900e+09,2.070000e+10,3.154000e+09,4.946807e+09,1.613500e+10,2.285000e+09,1.018500e+10,1.455400e+10,1.600000e+09,8.650000e+08,26368000.0,4.984956e+09,3.749360e+11
1Q2021,3.132000e+10,5.495000e+10,7.760000e+10,6.720000e+10,2.246900e+09,1.860000e+10,1.200000e+09,3.646115e+09,1.514800e+10,6.650000e+08,5.964000e+09,5.728000e+09,1.300000e+09,1.768000e+09,43314000.0,4.043107e+09,2.914224e+11
2Q2021,2.968000e+10,5.558200e+10,1.004000e+11,9.110000e+10,2.098800e+09,4.490000e+10,2.100000e+10,3.646115e+09,1.302200e+10,5.355000e+09,6.609000e+09,5.020000e+09,2.300000e+09,1.945000e+09,38796000.0,4.692425e+09,3.873891e+11
3Q2021,5.078000e+10,5.391200e+10,1.004000e+11,1.481000e+11,1.807700e+09,1.330000e+10,1.890000e+10,3.646115e+09,1.184200e+10,4.337000e+09,1.103100e+10,5.772000e+09,1.100000e+09,3.609000e+09,50648000.0,3.059742e+09,4.316472e+11

In [75]:
##### 게임시장 매출

sales_all = pd.read_csv("checkpoint/gamesales_all_checkpoint.csv",index_col = 0)

sales_all_sum = sales_all.T.loc[:, "Sum"]
sales_all_sum

1Q2017    2.049056e+12
2Q2017    1.458523e+12
3Q2017    2.051440e+12
4Q2017    1.836915e+12
1Q2018    2.473959e+12
2Q2018    1.727453e+12
3Q2018    1.923482e+12
4Q2018    1.899634e+12
1Q2019    2.228777e+12
2Q2019    1.858589e+12
3Q2019    1.889315e+12
4Q2019    1.970767e+12
1Q2020    2.442203e+12
2Q2020    2.261376e+12
3Q2020    2.481031e+12
4Q2020    2.317881e+12
1Q2021    2.525152e+12
2Q2021    2.181218e+12
3Q2021    2.669047e+12
Name: Sum, dtype: float64

In [76]:
# 통합

result = pd.concat([sales3C_mobile,sales3C_pc, temperature, marketing_cost_sum, sales_all_sum],axis=1)
result

        3사 Mobile 매출       3사 PC매출   평균기온(°C)        분기별 합계           Sum
1Q2017  1.907603e+11  9.447470e+11   2.744561  1.858444e+11  2.049056e+12
2Q2017  5.611863e+11  7.456180e+11  17.886667  2.045050e+11  1.458523e+12
3Q2017  9.005560e+11  9.349635e+11  24.000000  2.372769e+11  2.051440e+12
4Q2017  8.958130e+11  7.834570e+11   7.394386  2.862413e+11  1.836915e+12
1Q2018  7.269950e+11  7.692030e+11   2.030175  2.416348e+11  2.473959e+12
2Q2018  5.324043e+11  7.308540e+11  17.555088  2.368410e+11  1.727453e+12
3Q2018  5.921097e+11  1.092198e+12  24.640351  2.473202e+11  1.923482e+12
4Q2018  5.627087e+11  7.497090e+11   7.538947  2.762086e+11  1.899634e+12
1Q2019  3.239240e+11  9.549040e+11   3.451228  2.448007e+11  2.228777e+12
2Q2019  3.402707e+11  8.318520e+11  17.073776  2.597875e+11  1.858589e+12
3Q2019  3.123433e+11  1.105410e+12  24.010140  2.346793e+11  1.889315e+12
4Q2019  4.391200e+11  9.208410e+11   9.167368  2.820933e+11  1.970767e+12
1Q2020  1.048860e+12  1.593336e+12   4.849123  2.347716e+11  2.442203e+12
2Q2020  8.875083e+11  1.240709e+12  16.954737  2.838224e+11  2.261376e+12
3Q2020  1.356090e+12  1.453089e+12  23.112281  3.233597e+11  2.481031e+12
4Q2020  1.161611e+12  1.306676e+12   7.912281  3.749360e+11  2.317881e+12
1Q2021  9.742760e+11  1.815808e+12   4.052632  2.914224e+11  2.525152e+12
2Q2021  8.964657e+11  1.166518e+12  17.236268  3.873891e+11  2.181218e+12
3Q2021  8.974830e+11  1.553097e+12  24.183158  4.316472e+11  2.669047e+12

In [77]:
result.rename(columns={'분기별 합계':'마케팅 비용'}, inplace = True)
result.rename(columns={'Sum':'게임시장 규모'}, inplace = True)

In [83]:
result

        3사 Mobile 매출       3사 PC매출   평균기온(°C)        마케팅 비용       게임시장 규모
1Q2017  1.907603e+11  9.447470e+11   2.744561  1.858444e+11  2.049056e+12
2Q2017  5.611863e+11  7.456180e+11  17.886667  2.045050e+11  1.458523e+12
3Q2017  9.005560e+11  9.349635e+11  24.000000  2.372769e+11  2.051440e+12
4Q2017  8.958130e+11  7.834570e+11   7.394386  2.862413e+11  1.836915e+12
1Q2018  7.269950e+11  7.692030e+11   2.030175  2.416348e+11  2.473959e+12
2Q2018  5.324043e+11  7.308540e+11  17.555088  2.368410e+11  1.727453e+12
3Q2018  5.921097e+11  1.092198e+12  24.640351  2.473202e+11  1.923482e+12
4Q2018  5.627087e+11  7.497090e+11   7.538947  2.762086e+11  1.899634e+12
1Q2019  3.239240e+11  9.549040e+11   3.451228  2.448007e+11  2.228777e+12
2Q2019  3.402707e+11  8.318520e+11  17.073776  2.597875e+11  1.858589e+12
3Q2019  3.123433e+11  1.105410e+12  24.010140  2.346793e+11  1.889315e+12
4Q2019  4.391200e+11  9.208410e+11   9.167368  2.820933e+11  1.970767e+12
1Q2020  1.048860e+12  1.593336e+12   4.849123  2.347716e+11  2.442203e+12
2Q2020  8.875083e+11  1.240709e+12  16.954737  2.838224e+11  2.261376e+12
3Q2020  1.356090e+12  1.453089e+12  23.112281  3.233597e+11  2.481031e+12
4Q2020  1.161611e+12  1.306676e+12   7.912281  3.749360e+11  2.317881e+12
1Q2021  9.742760e+11  1.815808e+12   4.052632  2.914224e+11  2.525152e+12
2Q2021  8.964657e+11  1.166518e+12  17.236268  3.873891e+11  2.181218e+12
3Q2021  8.974830e+11  1.553097e+12  24.183158  4.316472e+11  2.669047e+12

In [ ]:
#### 체크포인트
result.to_csv("checkpoint/result_checkpoint.csv", encoding= "utf=8")